# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  chromatic:
    name: 'Run Chromatic'
    runs-on: ubuntu-latest

    # Job steps
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Change directory to taskbox and install dependencies using npm
      - name: Install dependencies
        run: |
          cd taskbox
          npm install

      # Run Chromatic in the taskbox directory
      - name: Publish to Chromatic
        run: |
          cd taskbox
          npx chromatic --project-token=chpt_e904b02057d0a9a
